config/routes.rb
Rails.application.routes.draw do
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)

  devise_for :users, controllers: { registrations: 'users/registrations' }
  # , omniauth_callbacks: 'omniauth_callbacks'
  # devise_for :users, :controllers => { :omniauth_callbacks => "omniauth_callbacks" }




  devise_scope :user do
    root to: 'users/registrations#edit'
  end



  resource :user, only: [:edit] do
    collection do
      patch 'update_password'
      patch 'update'
    end
  end

  # kiosk will be shown as donations while receiving donations..like http://paynow.io/donations/1001
  resources :kiosks
  
  namespace :dashboard do
    get 'vt', to: '/kiosks#vt'
    get 'reporting', to: '/kiosks#reporting'
    get 'donation_detail', to: '/kiosks#donation_detail'
    get 'bin', to: '/kiosks#bin'
    get 'online', to: '/kiosks#online'
    get 'contactless', to: '/contactless#show'
    post 'terminalsetup', to: '/contactless#terminalsetup'

    post 'online', to: '/kiosks#submit_online'
    post 'refund', to: '/kiosks#refund'
    post 'update_kiosk_profile', to: '/kiosks#update_profile'
    post 'update_kiosk_pref', to: '/kiosks#update_kiosk_pref'
    post 'sendreceipt', to: '/kiosks#sendreceipt'
    post 'slugupdate', to: '/kiosks#slugupdate'
    post 'ajx_charge_s1', to: '/pay#ajx_charge_s1'
    post 'ajx_charge_s2', to: '/pay#ajx_charge_s2'
    post 'update_notif_pref', to: '/users#update_notif_pref'

    get 'capture' , to: '/pay#capture'
    
  end
  resources :activations
  resources :terms, only: [:index]


  #need to find a way for /secure/
  #resources :pay, path: :secure
  get 'secure/:kid', to: 'pay#show'
  resources :pay, path: '' do
   
  
   end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :trackable, :rememberable, :validatable
  attr_accessor  :terms, :current_password
  before_create :build_default_kiosk



 


  has_one :kiosk
  has_many :donations, foreign_key: "donated_by"
  accepts_nested_attributes_for(:kiosk, update_only: true)
  # def self.find_for_database_authentication(warden_conditions)
  #   conditions = warden_conditions.dup
  #   if login = conditions.delete(:login)
  #     where(conditions.to_h).where(['lower(username) = :value OR lower(email) = :value', { value: login.downcase }]).first
  #   else
  #     where(conditions.to_h).first
  #   end
  # end
end

private
def build_default_kiosk
  # build default profile instance. Will use default params.
  # The foreign key to the owning User model is set automatically
  build_kiosk
  true # Always return true in callbacks as the normal 'continue' state
  # Assumes that the default_profile can **always** be created.
  # or
  # Check the validation of the profile. If it is not valid, then
  # return false from the callback. Best to use a before_validation
  # if doing this. View code should check the errors of the child.
  # Or add the child's errors to the User model's error array of the :base
  # error item
end

app/controllers/users/registrations_controller.rb
class Users::RegistrationsController < Devise::RegistrationsController
  # before_filter :configure_sign_up_params, only: [:create]
  # before_filter :configure_account_update_params, only: [:update]
  prepend_before_action :authenticate_scope!, only: [:change_password]

  layout :set_layout
  def set_layout
     if current_user
       'dashboard'
     else
       'auth'
     end
  end
  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
   def edit

     



     if current_user
      if(current_user.kiosk)
        @collection =  Donation.where(kiosk_id: current_user.kiosk.id).where("tx_status = 'Approved'").sum(:amount)
        @gateway_fee = Donation.where(kiosk_id: current_user.kiosk.id).where("tx_status = 'Approved'").sum(:gateway_fee)
        super
      end  



    else
      redirect_to "/users/sign_in"

    end

    
    


  end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.for(:sign_up) << :attribute
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.for(:account_update) << :attribute
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end

  protected

  def update_resource(resource, params)
    resource.update_without_password(params)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action  :authenticate_user!

  def edit
    @user = current_user


    
  end

  def delete_stripe
    @user = User.find(current_user.id)
    @user.update_attributes({
                              provider: nil,
                              uid: nil,
                              access_code: nil,
                              publishable_key: nil
                            })
    @user.save
    redirect_to root_path
  end


  def update
    @user = User.find(current_user.id)
    if @user.update(user_profile_params)
     redirect_to edit_user_path(current_user)
    else
      redirect_to edit_user_path(current_user)
    end
  end

  def update_notif_pref
    @user = User.find(current_user.id)
    if @user.update(user_profile_params)

    end

  end

  def update_password
    @user = User.find(current_user.id)
    user_params[:password_changed_at] = Time.new
    res = @user.update_with_password(user_params)
    if res

      # Sign in the user by passing validation in case their password changed
      sign_in @user, bypass: true
      render json: {
        success: true
      }, status: 200
    else
      #render :json => @user.errors.messages, :status => :bad_request
      render json: {
        error: @user.errors.messages,
      }, status: 400
     end
  end

  private

  def user_params
    # NOTE: Using `strong_parameters` gem
    params.require(:user).permit(:password, :password_confirmation, :current_password)
  end


  def user_profile_params
    # NOTE: Using `strong_parameters` gem
    params.require(:user).permit(:email, :fname, :lname, :phone, :tz, :notify_sms_hpp, :notify_email_hpp, :notify_email_daily, :notify_email_monthly, :dark_mode)
  end
end

app/views/users/_notifications.html.erb

                         <div class="tab-pane" id="notifications">
                           
     <div class="nk-block">



                                    <div class="nk-block-head nk-block-head-sm">
                                        <div class="nk-block-head-content">
                                            <h6>SMS Text Messages</h6>
                                            <p>These messages are instant.</p>
                                        </div>
                                    </div><!-- .nk-block-head -->
                                    <div class="nk-block-content">
                                        <div class="gy-3">
                                            <div class="g-item">
                                                <div class="custom-control custom-switch">

                                            <% if @user.notify_sms_hpp %>
                                                <input type="checkbox" class="custom-control-input" id="hpp-sms"  checked>

                                            <% else %>
                                                <input type="checkbox" class="custom-control-input" id="hpp-sms">
                                            <% end %>


                                                   
                                                    <label class="custom-control-label" for="hpp-sms">Receive a text message each time someone pays on my hosted payment page.</label>
                                                </div>
                                            </div>

                                        </div>
                                    </div><!-- .nk-block-content -->
                                    <div class="nk-block-head nk-block-head-sm">
                                        <div class="nk-block-head-content">
                                            <h6>Email</h6>
                                            <p>Select which email notifications you would like to receive.</p>
                                        </div>
                                    </div><!-- .nk-block-head -->
                                    <div class="nk-block-content">
                                        <div class="gy-3">
                                            <div class="g-item">
                                                <div class="custom-control custom-switch">
                                                   

                                                      <% if @user.notify_email_hpp %>
                                                <input type="checkbox" class="custom-control-input" id="hpp-email"  checked>

                                            <% else %>
                                                <input type="checkbox" class="custom-control-input" id="hpp-email">
                                            <% end %>


                                                    <label class="custom-control-label" for="hpp-email">Receive an email each time someone pays on my hosted payment page.</label>
                                                </div>
                                            </div>
                                            <div class="g-item">
                                                <div class="custom-control custom-switch">

                                                 <% if @user.notify_email_daily %>
                                                <input type="checkbox" class="custom-control-input" id="hpp-daily"  checked>

                                            <% else %>
                                                <input type="checkbox" class="custom-control-input" id="hpp-daily">
                                            <% end %>


                                               


                                                    <label class="custom-control-label" for="hpp-daily">Receive an email at the end of each day with your activity and totals.</label>
                                                </div>
                                            </div>
                                            <div class="g-item">
                                                <div class="custom-control custom-switch">

                                                  <% if @user.notify_email_monthly %>
                                                <input type="checkbox" class="custom-control-input" id="hpp-monthly"  checked>

                                            <% else %>
                                                <input type="checkbox" class="custom-control-input" id="hpp-monthly">
                                            <% end %>

                                                 
                                                    <label class="custom-control-label" for="hpp-monthly">Receive an email at the end of each month with your summary activity and totals.</label>
                                                </div>
                                            </div>
                                        </div>
                                    </div><!-- .nk-block-content -->



                                </div><!-- .nk-block -->

                                </div>

app/views/users/_security.html.erb

                         <div class="tab-pane" id="security">
                                   <div class="nk-block">
                                    <div class="nk-block-head">
                                        <div class="nk-block-head-content">
                                            <h5 class="nk-block-title">Security Settings</h5>
                                            <div class="nk-block-des">
                                                <p>These settings are helps you keep your account secure.</p>
                                            </div>
                                        </div>
                                    </div><!-- .nk-block-head -->
                                    <div class="card card-bordered">
                                        <div class="card-inner-group">

                                            <div class="card-inner">
                                                <div class="between-center flex-wrap flex-md-nowrap g-3">
                                                    <div class="nk-block-text">
                                                        <h6>Change Password</h6>
                                                        <p>Set a unique password to protect your account.</p>
                                                    </div>
                                                    <div class="nk-block-actions flex-shrink-sm-0">
                                                        <ul class="align-center flex-wrap flex-sm-nowrap gx-3 gy-2">
                                                            <li class="order-md-last">
                                                                <a href="#"  class="btn btn-primary"  data-toggle="modal" data-target="#profile-pwd">Change Password</a>
                                                            </li>
                                                            <li><!-- Temp Hidden
                                                                <em class="text-soft text-date fs-12px">Last changed: <span>
                                                                <%=(@user.password_changed_at)?
                                                                @user.password_changed_at.strftime("%^b %d, %Y %H:%M %p"): '-' %>
                                                              </span></em>
                                                                -->
                                                            </li>
                                                        </ul>
                                                    </div>
                                                </div>
                                            </div><!-- .card-inner -->

                                        </div><!-- .card-inner-group -->
                                    </div><!-- .card -->


                                </div><!-- .nk-block -->

                                </div>









  <%= form_for(@user, :url => { :action => "update_password"  }, :remote => true, :html => {:class => "update_password"}, data: {type: 'json'} ) do |f| %>


  <!-- @@ Profile Edit Modal @e -->
                <div class="modal fade" tabindex="-1" role="dialog" id="profile-pwd">
                    <div class="modal-dialog modal-dialog-centered modal-lg" role="document">
                        <div class="modal-content">
                            <a href="#" class="close" data-dismiss="modal"><em class="icon ni ni-cross-sm"></em></a>
                            <div class="modal-body modal-body-lg">


                                <h5 class="title">Change Password</h5>


                                                      <% if @user.errors.any? %>


    <% @user.errors.full_messages.each do |msg| %>
      <div class="alert alert-danger" role="alert"><%= msg %></div>
    <% end %>

<% end %>

                                        <div class="row gy-4">

                                            <div class="col-md-6">
                                                <div class="form-group">
                                                    <label class="form-label" for="language">Current Password</label>

                                                     <%= f.password_field :current_password, autocomplete: "off", :placeholder => "", :class => "form-control",:required => true %>
                                                </div>
                                            </div>
                                            </div>
                                             <div class="row gy-4">
                                            <div class="col-md-6">
                                                <div class="form-group">

                                                    <label class="form-label" for="time-zone">New Password</label>

                                                     <%= f.password_field :password, autocomplete: "off", :placeholder => "", :class => "form-control",:required => true %>


                                                </div>
                                            </div>


                                            <div class="col-md-6">
                                                <div class="form-group">

                                                    <label class="form-label" for="time-zone">Confirm Password</label>

                                                     <%= f.password_field :password_confirmation, autocomplete: "off", :placeholder => "", :class => "form-control",:required => true %>


                                                </div>
                                            </div>


                                            <div class="col-12">
                                                <ul class="align-center flex-wrap flex-sm-nowrap gx-4 gy-2">
                                                    <li>
                                                          <%= f.submit "Save", :class => "btn btn-lg btn-primary" %>
                                                    </li>
                                                    <li>
                                                        <a href="#" data-dismiss="modal" class="link link-light">Cancel</a>
                                                    </li>
                                                </ul>
                                            </div>



 <div class="col-12 ">
    <div class="alert alert-danger d-none text-capitalize"  id="pwd-err">
    </div>
 </div>
                                        </div>

                            </div><!-- .modal-body -->
                        </div><!-- .modal-content -->
                    </div><!-- .modal-dialog -->
                </div><!-- .modal -->

<% end %>

app/views/users/_success.html.erb
                            <!-- Modal -->
  <div class="modal-dialog">

    <!-- Modal content-->
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal">&times;</button>
        <h4 class="modal-title">Change Password</h4>
      </div>
      <div class="modal-body">

      <div class="alert alert-success">
  		<strong>Done!</strong> Password changed successfully
	  </div>


      </div>


      <div class="modal-footer">
        <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
      </div>
    </div>

  </div>
</div>

app/views/users/_yourbusinessmodal.html.erb



  <%= form_for(@user.kiosk, :url => dashboard_update_kiosk_profile_path, :method => "post") do |f| %>

      <!-- @@ Profile Edit Modal @e -->
                <div class="modal fade" tabindex="-1" role="dialog" id="business-edit">
                    <div class="modal-dialog modal-dialog-centered modal-lg" role="document">
                        <div class="modal-content">
                            <a href="#" class="close" data-dismiss="modal"><em class="icon ni ni-cross-sm"></em></a>
                            <div class="modal-body modal-body-lg">
                                <h5 class="title">Update Profile</h5>
                                <ul class="nk-nav nav nav-tabs">
                                    <li class="nav-item">
                                        <a class="nav-link" data-toggle="tab" href="#business1">Contact</a>
                                    </li>
                                    <li class="nav-item">
                                        <a class="nav-link" data-toggle="tab" href="#address">Address</a>
                                    </li>
                                </ul><!-- .nav-tabs -->
                                <div class="tab-content">
                                    <div class="tab-pane" id="business1">
                                        <div class="row gy-4">
                                            <div class="col-md-6">
                                                <div class="form-group">
                                                    <label class="form-label" for="business-name">Business Name</label>


                                                    <%= f.text_field :title,   :placeholder => "Owner's first name?", :class => "form-control  form-control-lg" %>



                                                </div>
                                            </div>
                                            <div class="col-md-6">
                                                <div class="form-group">
                                                    <label class="form-label" for="slogan">Slogan</label>
                                                    <%= f.text_field :slogan,   :placeholder => "Does your company have a slogan?", :class => "form-control  form-control-lg" %>

                                                </div>
                                            </div>
                                            <div class="col-md-6">
                                                <div class="form-group">
                                                    <label class="form-label" for="phone">Phone Number</label>

                                                     <%= f.text_field :sms_number,   :placeholder => "Phone number of the business?", :class => "form-control  form-control-lg phone-format" %>



                                                </div>
                                            </div>
                                            <div class="col-md-6">
                                                <div class="form-group">
                                                    <label class="form-label" for="birth-day">Website </label>

                                                         <%= f.text_field :website,   :placeholder => "Does your company have a website?", :class => "form-control  form-control-lg" %>


                                                </div>
                                            </div>

                                            <div class="col-12">
                                                <ul class="align-center flex-wrap flex-sm-nowrap gx-4 gy-2">
                                                    <li>

                                                      <%= f.submit "Save", :class => "btn btn-lg btn-primary" %>



                                                    </li>
                                                    <li>
                                                        <a href="#" data-dismiss="modal" class="link link-light">Cancel</a>
                                                    </li>
                                                </ul>
                                            </div>
                                        </div>
                                    </div><!-- .tab-pane -->
                                    <div class="tab-pane" id="address">
                                        <div class="row gy-4">
                                            <div class="col-md-6">
                                                <div class="form-group">
                                                    <label class="form-label" for="address">Street Address</label>

                                                     <%= f.text_field :staddr,   :placeholder => "What is the physical address?", :class => "form-control  form-control-lg" %>


                                                </div>
                                            </div>
                                            <div class="col-md-6">
                                                <div class="form-group">
                                                    <label class="form-label" for="city">City</label>

<%= f.text_field :city,   :placeholder => "What city is your business located in?", :class => "form-control  form-control-lg" %>



                                                </div>
                                            </div>
                                            <div class="col-md-6">
                                                <div class="form-group">
                                                    <label class="form-label" for="zip">Zip Code</label>

<%= f.text_field :zip,   :placeholder => "Which zip code is your business located in?", :class => "form-control " %>


                                                </div>
                                            </div>
                                            <div class="col-md-6">
                                                <div class="form-group">
                                                  <label class="form-label" for="state">State</label>

                                                    <%= f.select(:state, options_for_select(us_states.invert, @user.kiosk.state),{}, {:class => "form-select"} ) %>





                                                </div>
                                            </div>
                                            <div class="col-12">
                                                <ul class="align-center flex-wrap flex-sm-nowrap gx-4 gy-2">
                                                    <li>

                                                        <%= f.submit "Save", :class => "btn btn-lg btn-primary" %>



                                                    </li>
                                                    <li>
                                                        <a href="#" data-dismiss="modal" class="link link-light">Cancel</a>
                                                    </li>
                                                </ul>
                                            </div>
                                        </div>
                                    </div><!-- .tab-pane -->
                                </div><!-- .tab-content -->
                            </div><!-- .modal-body -->
                        </div><!-- .modal-content -->
                    </div><!-- .modal-dialog -->
                </div><!-- .modal -->

<% end %>

app/views/users/edit.html.erb



  <div class="nk-content nk-content-lg nk-content-fluid">
                    <div class="container-xl wide-lg">
                        <div class="nk-content-inner">
                            <div class="nk-content-body">
                                <div class="nk-block-head">
                                    <div class="nk-block-head-content">
                                        <h2 class="nk-block-title fw-normal">Account Setting</h2>
                                        <div class="nk-block-des">
                                            <p>You have full control to manage your own account setting. <span class="text-primary"><em class="icon ni ni-info"></em></span></p>
                                        </div>
                                    </div>
                                </div><!-- .nk-block-head -->
                                <ul class="nk-nav nav nav-tabs">
                                    <li class="nav-item">
                                        <a class="nav-link active" href="#yourac"  data-toggle="tab">Your Account</a>
                                    </li>
                                    <li class="nav-item">
                                        <a class="nav-link" href="#yourbusiness" data-toggle="tab">Your Business</a>
                                    </li>
                                    <li class="nav-item">
                                        <a class="nav-link" href="#security" data-toggle="tab">Security</a>
                                    </li>
                                    <li class="nav-item">
                                        <a class="nav-link" href="#notifications" data-toggle="tab">Notifications</a>
                                    </li>

                                </ul><!-- .nav-tabs -->



          <div class="tab-content">
          <%= render "yourac" %>
          <%= render "yourbusiness" %>
          <%= render "security" %>
          <%= render "notifications" %>
          </div>



                            </div>
                        </div>
                    </div>
                </div>




   <%= render "youracmodal" %>
  <%= render "yourbusinessmodal" %>


app/views/users/success.js.erb
$("#product-modal").html("<%= escape_javascript(render 'success') %>")
$("#product-modal").modal({show:false})