config/routes.rb
Rails.application.routes.draw do
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)

  devise_for :users, controllers: { registrations: 'users/registrations' }
  # , omniauth_callbacks: 'omniauth_callbacks'
  # devise_for :users, :controllers => { :omniauth_callbacks => "omniauth_callbacks" }




  devise_scope :user do
    root to: 'users/registrations#edit'
  end



  resource :user, only: [:edit] do
    collection do
      patch 'update_password'
      patch 'update'
    end
  end

  # kiosk will be shown as donations while receiving donations..like http://paynow.io/donations/1001
  resources :kiosks
  
  namespace :dashboard do
    get 'vt', to: '/kiosks#vt'
    get 'reporting', to: '/kiosks#reporting'
    get 'donation_detail', to: '/kiosks#donation_detail'
    get 'bin', to: '/kiosks#bin'
    get 'online', to: '/kiosks#online'
    get 'contactless', to: '/contactless#show'
    post 'terminalsetup', to: '/contactless#terminalsetup'

    post 'online', to: '/kiosks#submit_online'
    post 'refund', to: '/kiosks#refund'
    post 'update_kiosk_profile', to: '/kiosks#update_profile'
    post 'update_kiosk_pref', to: '/kiosks#update_kiosk_pref'
    post 'sendreceipt', to: '/kiosks#sendreceipt'
    post 'slugupdate', to: '/kiosks#slugupdate'
    post 'ajx_charge_s1', to: '/pay#ajx_charge_s1'
    post 'ajx_charge_s2', to: '/pay#ajx_charge_s2'
    post 'update_notif_pref', to: '/users#update_notif_pref'

    get 'capture' , to: '/pay#capture'
    
  end
  resources :activations
  resources :terms, only: [:index]


  #need to find a way for /secure/
  #resources :pay, path: :secure
  get 'secure/:kid', to: 'pay#show'
  resources :pay, path: '' do
   
  
   end
end

app/models/activation.rb
class Activation < ApplicationRecord
  validates :title, presence: true
  validates :name, presence: true
  validates :phone, presence: true
end

app/controllers/activations_controller.rb
class ActivationsController < ApplicationController
  def new
    # logger.info params.inspect

    # logger.info response.inspect

    @activation = Activation.new
  end

  def create
    @activation = Activation.new(activation_params)
    if @activation.save
      ActivationMailer.activation_email(@activation).deliver

      render 'success'
    end
  end

  private

  def activation_params
    params.require(:activation).permit(:title, :name, :phone, :email)
  end
end

app/helpers/activations_helper.rb
module ActivationsHelper
end

app/views/activations/new.html.erb
<!-- START PAGE-CONTAINER -->
<div class="page-container">
  <!-- START PAGE HEADER WRAPPER -->
  <!-- START HEADER -->
  <div class="header hidden-xs hidden-sm hidden-md">
    <div class=" pull-left sm-table">
      <div class="header-inner">

      <h2 class="pull-left p-l-30"><strong>PayNow.io</strong></h2>
 



        <div class="brand inline">
          <!--
<img src="assets/img/logo.png" alt="logo" data-src="assets/img/logo.png" data-src-retina="assets/img/logo_2x.png" width="78" height="22">

-->
        </div>

      </div>
    </div>
    <div class=" pull-right">
      <!-- START User Info-->
      <div class="visible-lg visible-md m-t-10">
        <div class="pull-left p-r-10 p-t-10 fs-16 font-heading">
          <span class="semi-bold">Secure</span> <span class="text-master">Form</span>
        </div>

        <div class="dropdown pull-right"><button class="profile-dropdown-toggle" type="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
            <span class="thumbnail-wrapper d32 circular inline m-t-5">
                       <%= image_tag("avatar.jpg", :alt => "", :size => "32x32",  data: { src: "avatar.jpg", src_retina: "avatar_small2x.jpg" }) %>


        </span>

          </button>

          <%= link_to('Logout', destroy_user_session_path, :method => :delete) %></div>


      </div>
      <!-- END User Info-->
    </div>
  <!-- END HEADER -->
</div>
<!-- Modal -->



<!-- START PAGE CONTENT WRAPPER -->
  <div class="page-content-wrapper">
    <!-- START PAGE CONTENT -->


      <!-- START CONTAINER FLUID -->
      <div class="container-fluid container-fixed-lg bg-white">





        <!-- START PANEL -->
        <div class="panel panel-transparent">
          <div class="panel-heading">
          </div>
          <div class="panel-body">
            <div class="row">
              <div class="col-sm-10">
                <h3>Merchant Account</h3>
                <p>Setting up a merchant account is fairly easy. PayNow.io is directly integrated into many different processors. Please complete your information below, we will help you get integrated right away. If you do not have a processor, no problem, we will help get one setup for you.

                </p>
                <br>


                <%= form_for :activation ,html: {class: "form-horizontal" } , url: activations_path  do |ff| %>

                  <% if @activation.errors.any? %>
                      <div id="error_explanation">
                        <h2>
                          <%= pluralize(@activation.errors.count, "error") %> prohibited
                          this form being sent:
                        </h2>
                        <ul>
                          <% @activation.errors.full_messages.each do |msg| %>
                            <li><%= msg %></li>
                          <% end %>
                        </ul>
                      </div>
                    <% end %>


                <div class="form-group m-t-0">
                    <label for="fname" class="col-sm-3 control-label">Name of Organization</label>
                  <div class="col-sm-9">
                    <%= ff.text_field :title, :placeholder => "What is the business name that you want listed on customer receipts.", :class => "form-control", :maxlength => 200, :required => true%>
                  </div>
                </div>


                <div class="form-group ">
                  <label for="fname" class="col-sm-3 control-label">Contact Name</label>
                  <div class="col-sm-9">
                    <%= ff.text_field :name, :placeholder => "Who are we calling?", :class => "form-control", :maxlength => 150, :required => true%>
                  </div>
                </div>

                  <div class="form-group">
                    <label for="fname" class="col-sm-3 control-label">Phone</label>
                    <div class="col-sm-9">
                      <%= ff.text_field :phone, :placeholder => "Example: 818-555-9282", :class => "form-control", :maxlength => 20, :required => true%>
                    </div>
                  </div>

                  <div class="form-group">
                    <label for="fname" class="col-sm-3 control-label">Email</label>
                    <div class="col-sm-9">
                      <%= ff.text_field :email, :placeholder => "Example: psmith@gmail.com", :class => "form-control", :maxlength => 150, :required => true%>
                    </div>
                  </div>

                  <br>
                  <div class="row col-sm-12">
                    <div class="col-sm-6">
                    <%= ff.submit "Send", :class => "btn btn-success" %>

                  </div>
                  </div>

                <% end %>

              </div>
            </div>
          </div>
        </div>
        <!-- END PANEL -->
      </div>
      <!-- END CONTAINER FLUID -->
    </div>
    <!-- END PAGE CONTENT -->




<div id="product-modal" class="modal fade">

</div>

    <!-- START FOOTER -->

    <!-- END FOOTER -->
  </div>
  <!-- END PAGE CONTENT WRAPPER -->
</div>
<!-- END PAGE CONTAINER -->

app/views/activations/success.html.erb
<!-- START PAGE-CONTAINER -->
    <div class="page-container">
      <!-- START PAGE HEADER WRAPPER -->
      <!-- START HEADER -->
      <div class="header ">
        <div class=" pull-left sm-table">
          <div class="header-inner">

         
          <h3 class="pull-left p-l-30"><strong>Thank you!</strong></h3>

            <div class="brand inline">
              <!--
<img src="assets/img/logo.png" alt="logo" data-src="assets/img/logo.png" data-src-retina="assets/img/logo_2x.png" width="78" height="22">

-->
            </div>

          </div>
        </div>
        <div class=" pull-right hidden-xs hidden-sm hidden-md">
          <!-- START User Info-->
          <div class="visible-lg visible-md m-t-10">
            <div class="pull-left p-r-10 p-t-10 fs-16 font-heading">
              <span class="semi-bold">Secure</span> <span class="text-master">Form</span>
            </div>
            <div class="dropdown pull-right">
              <button class="profile-dropdown-toggle" type="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                <span class="thumbnail-wrapper d32 circular inline m-t-5">
                <%= image_tag("avatar.jpg", :alt => "", :size => "32x32",  data: { src: "avatar.jpg", src_retina: "avatar.jpg" }) %>
            </span>
              </button>
            </div>
          </div>
          <!-- END User Info-->
        </div>
      <!-- END HEADER -->
    </div>


    <!-- START PAGE-CONTAINER -->
    <div class="page-container pull-left">






           <!-- START PAGE CONTENT WRAPPER -->
<!--       <div class="page-content-wrapper"> -->
        <!-- START PAGE CONTENT -->
        <div class="content">
          <!-- START CONTAINER FLUID -->
          <div class="container-fluid container-fixed-lg">
            <div id="rootwizard">
              <!-- Nav tabs -->
              <ul class="nav nav-tabs nav-tabs-linetriangle nav-tabs-separator ">

                <li class="">
                  <a data-toggle="tab" href="#tab3"><i class="fa fa-check tab-icon"></i> <span>Done</span></a>
                </li>
              </ul>
              <!-- Tab panes -->
              <div class="tab-content">





                <div class="tab-pane slide-left padding-20" id="tab3">
						<h2>We will reach out to you shortly.</h2>
                    <br />
                    
<br />
				</div>
 <div class="col-sm-6">

                        <%= link_to('Done', destroy_user_session_path, :method => :delete, :class => "btn btn-success" ) %></div>

                </div>









                </div>














              </div>

            </div>

          </div>

          <!-- END CONTAINER FLUID -->
<!--         </div> -->
        <!-- END PAGE CONTENT -->


  <%= render "layouts/footer" %>

      </div>
      <!-- END PAGE CONTENT WRAPPER -->
    </div>
    <!-- END PAGE CONTAINER -->