config/routes.rb
Rails.application.routes.draw do
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)

  devise_for :users, controllers: { registrations: 'users/registrations' }
  # , omniauth_callbacks: 'omniauth_callbacks'
  # devise_for :users, :controllers => { :omniauth_callbacks => "omniauth_callbacks" }




  devise_scope :user do
    root to: 'users/registrations#edit'
  end



  resource :user, only: [:edit] do
    collection do
      patch 'update_password'
      patch 'update'
    end
  end

  # kiosk will be shown as donations while receiving donations..like http://paynow.io/donations/1001
  resources :kiosks
  
  namespace :dashboard do
    get 'vt', to: '/kiosks#vt'
    get 'reporting', to: '/kiosks#reporting'
    get 'donation_detail', to: '/kiosks#donation_detail'
    get 'bin', to: '/kiosks#bin'
    get 'online', to: '/kiosks#online'
    get 'contactless', to: '/contactless#show'
    post 'terminalsetup', to: '/contactless#terminalsetup'

    post 'online', to: '/kiosks#submit_online'
    post 'refund', to: '/kiosks#refund'
    post 'update_kiosk_profile', to: '/kiosks#update_profile'
    post 'update_kiosk_pref', to: '/kiosks#update_kiosk_pref'
    post 'sendreceipt', to: '/kiosks#sendreceipt'
    post 'slugupdate', to: '/kiosks#slugupdate'
    post 'ajx_charge_s1', to: '/pay#ajx_charge_s1'
    post 'ajx_charge_s2', to: '/pay#ajx_charge_s2'
    post 'update_notif_pref', to: '/users#update_notif_pref'

    get 'capture' , to: '/pay#capture'
    
  end
  resources :activations
  resources :terms, only: [:index]


  #need to find a way for /secure/
  #resources :pay, path: :secure
  get 'secure/:kid', to: 'pay#show'
  resources :pay, path: '' do
   
  
   end
end

app/models/kiosk.rb
class Kiosk < ApplicationRecord
  belongs_to :user, class_name: 'User', foreign_key: 'user_id'
  validates_uniqueness_of :title

  attr_accessor :mail_content, :email, :subject

  has_many :donations

  accepts_nested_attributes_for :donations
end

app/controllers/kiosks_controller.rb
class KiosksController < BaseController

  def vt
    if (current_user && current_user.kiosk && current_user.kiosk.id)
      @kiosk = current_user.kiosk
      @user = current_user
      page = (params[:page]?params[:page]:1)
      @donations = current_user.kiosk.donations.order('id desc').page(page).per(20)
      @tz = current_user.tz
    else
      @kiosk = nil
      @user = nil
    end
    render 'show'

    #@kiosk = current_user.find(params[:id])
    #render 'show'
  end



  def online
    if (current_user && current_user.kiosk && current_user.kiosk.id)
      @kiosk = current_user.kiosk
      @donations = current_user.donations
      @collection =  Donation.where(kiosk_id: current_user.kiosk.id).where("tx_status = 'Approved'").sum(:amount)
      @gateway_fee = Donation.where(kiosk_id: current_user.kiosk.id).where("tx_status = 'Approved'").sum(:gateway_fee)

    else
      @kiosk = nil
    end


  end


  def submit_online



    if !params[:email].blank? && params[:email] != ''
      amount = params[:amount].sub(',','')
      url = params[:url]+"?inv_num=#{params[:inv_num]}&inv_desc=#{params[:inv_desc]}&amount=#{amount}"
      charge = { 'email' => params[:email],  'amount' => amount , 'kiosk_title' => params[:kiosk_title], 'url' => url , 'inv_num' => params[:inv_num], 'inv_desc' => params[:inv_desc], 'created_at' => DateTime.now.in_time_zone(current_user.tz).strftime("%^b %d, %Y %I:%M %p") }
      KioskMailer.online_email(charge).deliver
    end

  end






  def donation_detail
    donation = current_user.kiosk.donations.find(params[:id])

    temp = Hash.new

    temp["date"] = donation.created_at.in_time_zone(current_user.tz).strftime("%^b %d, %Y %H:%M %p")
    temp["id"] = donation.id
    temp["amount"] = ActiveSupport::NumberHelper.number_to_currency(donation.amount.to_f) 
    temp["name"] = donation.name
    temp["email"] = donation.email
    temp["merchid"] = donation.kiosk.user.merchid
    temp["authcode"] = donation.authcode
    temp["card_type"] = donation.card_type
    temp["gateway_fee"] = ActiveSupport::NumberHelper.number_to_currency(donation.gateway_fee)
    temp["status"] = donation.tx_status
    temp["total_charged"] = ActiveSupport::NumberHelper.number_to_currency(donation.amount.to_f +  donation.gateway_fee.to_f)

    temp["cardconnectref"] =  donation.cardconnectref
    temp["inv_num"] = donation.inv_num
    temp["inv_desc"] = donation.inv_desc
    temp["company"] = donation.company
    temp["tx_status"] = donation.tx_status
    temp["last4"] = donation.last4
    temp["tip_amt"] = ActiveSupport::NumberHelper.number_to_currency(donation.tip_amt)
    temp["emp"] = donation.emp



     #

    render :json => {:donation =>  temp }

  end

  def reporting

    respond_to do |format|

      if (current_user && current_user.kiosk && current_user.kiosk.id)
        format.html {
          render 'reporting'
        }
        format.json {
          page = (params[:page]?params[:page]:1)
          recs = current_user.kiosk.donations
          #recs = Donations.where(kiosk_id: current_user.kiosk.id)
          q  = params[:q]
          sort_order = params[:sort_order]
          sort_field = params[:sort_field]
          ctype =  params[:ctype]
          tx_status = params[:tx_status]

         # donations = donations.where("tx_status = ?", "refunded")
         if q 
            #don;t compare if it is too large..may be ref id
          if q.to_s =~ /\A[-+]?\d*\.?\d+\z/ and q.length < 7
            #if an int include id as well
            if Integer(q ,  exception: false)
              recs = recs.where("amount = ? OR gateway_fee = ? OR id = ?", q, q, q)
            else 
              #dont bother abt id
              recs = recs.where("amount = ? OR gateway_fee = ?", q, q)
            end

          else
            recs = recs.where("tx_status LIKE ? OR email LIKE ? OR name LIKE ? OR card_type LIKE ? OR cardconnectref LIKE ?", "%#{q}%", "%#{q}%", "%#{q}%", "%#{q}%", "%#{q}%")
          end
         end

         if ctype
          recs = recs.where("card_type LIKE ?", "%#{ctype}%")
         end

         if tx_status
          recs = recs.where("tx_status LIKE ?", "%#{tx_status}%")
         end

         order = 'id desc'
         if sort_field 
          order = "#{sort_field} #{sort_order}"
         end

         

         recs = recs.order(order).page(page).per(20)
          
          donations = []

          recs.each do |donation|  

            temp = Hash.new
            temp["date"] = donation.created_at.in_time_zone(current_user.tz).strftime("%^b %d, %Y %I:%M %p")
            temp["id"] = donation.id
            temp["amount"] = ActiveSupport::NumberHelper.number_to_currency(donation.amount) 
            temp["name"] = donation.name
            temp["card_type"] = donation.card_type
            temp["gateway_fee"] = ActiveSupport::NumberHelper.number_to_currency(donation.gateway_fee)
            temp["tx_status"] =  donation.tx_status
            temp["company"] =  donation.company
            temp["inv_num"] =  donation.inv_num
            temp["tip_amt"] =  ActiveSupport::NumberHelper.number_to_currency(donation.tip_amt)
           #
            donations.push(temp)
          end

          render :json => {:donations =>  donations, :total_count => recs.total_count, :kiosk_title => current_user.kiosk.title }
        }

      end
    end


    # if (current_user && current_user.kiosk && current_user.kiosk.id)
    #   render 'reporting'
    
    #   render :json => {:donations => @donations}

    # else
    #   @kiosk = nil
    #   @user = nil
    # end
    # render 'reporting'

  end



  def sendreceipt
    donation = Donation.find(params[:kiosk][:id])


    created_at = donation.created_at.in_time_zone(current_user.tz).strftime("%^b %d, %Y %I:%M %p")  
    KioskMailer.modal_receipt_email(donation, created_at).deliver

  end


  def slugupdate

    kiosk = Kiosk.find(params[:id])
    kiosk.slug = params[:slug]
    kiosk.save
   
   # KioskMailer.modal_receipt_email(donation).deliver

  end
  def refund 

    donation = Donation.find(params[:kiosk][:id])
    kiosk = donation.kiosk

    cred_combo = "#{kiosk.user.merchant_username}:#{kiosk.user.merchant_password}"


    rres = RestClient.get("#{kiosk.user.merchant_end_point}/cardconnect/rest/inquire/#{donation.cardconnectref}/#{kiosk.user.merchid}",  { 'Authorization' => 'Basic ' + Base64.strict_encode64(cred_combo), :content_type => 'application/json' })

    
    rresponse = JSON.parse(rres.body)

    if rresponse["voidable"] == "Y"

      cres = RestClient.post("#{kiosk.user.merchant_end_point}/cardconnect/rest/void", { 'merchid' => kiosk.user.merchid, 'retref' => donation.cardconnectref }.to_json, { 'Authorization' => 'Basic ' + Base64.strict_encode64(cred_combo), :content_type => 'application/json' })
      donation.tx_status = 'Voided'
    else

      
      cres = RestClient.post("#{kiosk.user.merchant_end_point}/cardconnect/rest/refund", { 'merchid' => kiosk.user.merchid, 'retref' => donation.cardconnectref }.to_json, { 'Authorization' => 'Basic ' + Base64.strict_encode64(cred_combo), :content_type => 'application/json' })

      donation.tx_status = 'Refunded'

    end


    cresponse = JSON.parse(cres.body)
    if cresponse['respstat'] == 'A'
      donation.save
  
      respond_to do |format|
        format.js { render :json => {:success => true,  status: :created }}
        format.html { render :json => {:success => true,  status: :created }}
        format.json { render :json => {:success => true,  status: :created }}

      end

    else
      respond_to do |format|
        format.js { render :json => {:success => false, :errors =>cresponse['resptext'], }, status: :unprocessable_entity  }
        format.html { render :json => {:success => false, :errors =>cresponse['resptext'], }, status: :unprocessable_entity  }
        format.json { render :json => {:success => false, :errors =>cresponse['resptext'], }, status: :unprocessable_entity  }

      end
   end


  end

  



  def new

  end

  def bin

    number = params[:number]
    first8dig = number.to_s[0..7]
    ccres = RestClient.get("https://lookup.binlist.net/#{first8dig}", { 'Accept-Version' => '3'})
    render json: ccres.body
  end


  
  def update
    id = params[:id]
    kiosk = Kiosk.find(id)

    number = params[:number]
    zip = params[:zip]
    cvc = params[:cvc]
    exp_mn = params[:exp_mn].to_s
    exp_yr = params[:exp_yr].to_s
    amount = params[:kiosk][:donations_attributes]['0'][:amount]
    orig_amt = 0
    fee = params[:kiosk][:donations_attributes]['0'][:fee_amt]
    service_fee = params[:kiosk][:donations_attributes]['0'][:service_fee]

    inv_num = params[:kiosk][:donations_attributes]['0'][:inv_num]
    inv_desc = params[:kiosk][:donations_attributes]['0'][:inv_desc]
    name = params[:kiosk][:donations_attributes]['0'][:name]
    email = params[:kiosk][:donations_attributes]['0'][:email]
    
    

    begin

       first8dig = number.to_s[0..7]
       last4 = number.to_s.last(4)
        ccres = RestClient.get("https://lookup.binlist.net/#{first8dig}", { 'Accept-Version' => '3'})
        ccbody = JSON.parse(ccres.body)
        ctype = 'credit'
        #no CC..no fee
        #if model is surcharge fee is only for credit card..determin if it is not a CC
        if ccbody["type"] != "credit"
          if kiosk.user.cmodel == 'surcharge'
            fee = 0
          end 
          ctype = 'debit'

        end 

        # no service fee if checkbox is disabled  
        if service_fee == "0"
          fee = 0
        end

        
      orig_amt = amount.to_f
      amount = amount.to_f + fee.to_f
      if amount < 0
        @response = { 'errors' => 'Invalid amount' }
      else
        cparams = { 'merchid' => kiosk.user.merchid, 'amount' => amount, 'expiry' => exp_mn + exp_yr, 'account' => number, 'currency' => 'USD', 'name' => name, 'ecomind' => 'E', 'cvv2' => cvc , 'postal' => zip,  'email' => email}

app/helpers/kiosks_helper.rb
module KiosksHelper
    def us_states
        return Hash["AL" =>"Alabama"	,"AK" =>"Alaska"	,"AZ" =>"Arizona"	,"AR" =>"Arkansas"	,"CA" =>"California"	,"CO" =>"Colorado"	,"CT" =>"Connecticut"	,"DE" =>"Delaware"	,"DC" =>"District Of Columbia"	,"FL" =>"Florida"	,"GA" =>"Georgia"	,"HI" =>"Hawaii"	,"ID" =>"Idaho"	,"IL" =>"Illinois"	,"IN" =>"Indiana"	,"IA" =>"Iowa"	,"KS" =>"Kansas"	,"KY" =>"Kentucky"	,"LA" =>"Louisiana"	,"ME" =>"Maine"	,"MD" =>"Maryland"	,"MA" =>"Massachusetts"	,"MI" =>"Michigan"	,"MN" =>"Minnesota"	,"MS" =>"Mississippi"	,"MO" =>"Missouri"	,"MT" =>"Montana"	,"NE" =>"Nebraska"	,"NV" =>"Nevada"	,"NH" =>"New Hampshire"	,"NJ" =>"New Jersey"	,"NM" =>"New Mexico"	,"NY" =>"New York"	,"NC" =>"North Carolina"	,"ND" =>"North Dakota"	,"OH" =>"Ohio"	,"OK" =>"Oklahoma"	,"OR" =>"Oregon"	,"PA" =>"Pennsylvania"	,"RI" =>"Rhode Island"	,"SC" =>"South Carolina"	,"SD" =>"South Dakota"	,"TN" =>"Tennessee"	,"TX" =>"Texas"	,"UT" =>"Utah"	,"VT" =>"Vermont"	,"VA" =>"Virginia"	,"WA" =>"Washington"	,"WV" =>"West Virginia"	,"WI" =>"Wisconsin"	,"WY" =>"Wyoming"]
    end
end

app/views/kiosks/invite.html.erb
<!-- START PAGE-CONTAINER -->
    <div class="page-container">
      <!-- START PAGE HEADER WRAPPER -->
      <!-- START HEADER -->
      <div class="header ">
        <div class=" pull-left sm-table">
          <div class="header-inner">

          <h3 class="pull-left p-l-30">Invite donors to <strong><%= @church.title %></strong></h3>

            <div class="brand inline">

            </div>

          </div>
        </div>

      <!-- END HEADER -->
    </div>


    <!-- START PAGE-CONTAINER -->
    <div class="page-container pull-left">







  <div class="content">
          <!-- START CONTAINER FLUID -->
          <div class="container-fluid container-fixed-lg">
            <div id="rootwizard">
              <!-- Nav tabs -->
              <ul class="nav nav-tabs nav-tabs-linetriangle nav-tabs-separator ">
                <li class="">
                  <a data-toggle="tab" href="#tab3"><i class="fa fa-check tab-icon"></i> <span>Send out an email</span></a>
                </li>
              </ul>
                <%= form_for(@church ,url: invite_churches_path(@church),  html: { method: :post  },) do |f| %>
              <!-- Tab panes -->
              <div class="tab-content">
                <div class="tab-pane active slide-left" id="tab1">

                    <div class="row">
                              <div class="padding-30">

                              <div class="col-md-7">
                                  <label>Email(s) - <i>Separated by commas</i></label>
                                   <%= f.text_field :email,  :placeholder => "john@example.com,mike@example.com", :class => "form-control"  %>
                              </div>
                             </div>
                            </div>



                    <div class="row">
                              <div class="padding-30">

                              <div class="col-md-7">
                                  <label>Subject</label>
                                   <%= f.text_field :subject,  :class => "form-control" , :value => "Your payments are greatly appreciated"  %>

                              </div>
                             </div>
                            </div>

                  <div class="row row-same-height">
                    <div class="col-md-12">
                      <div class="padding-30">

						   	 <%= f.text_area :mail_content ,:class => "wysihtml5", :cols => 100, :rows => 20, :value => " <br />Hi,<br />Getting involved in this good cause is a great way of going the extra mile to show your solidarity with our brothers and sisters around the world – and of getting your family and friends involved in our work too! <br />#{link_to 'Click here', church_url(@church)} to make your contribution. <br /><br /><br />Alternatively you should be able to simply copy this <b> #{church_url(@church)} </b> into the browser.<br /><br /><br /> Thank you!  " %>

                  </div>
                    </div>
                            <div class="col-md-7">
                      <div class="padding-30">

						   	  <%= f.submit "Send", :class => "btn btn-primary btn-cons pull-right" %>





                        </div>

                  </div>


                  </div>



                </div>




                </div>

        <% end %>


              </div>

            </div>

          </div>







          <!-- END CONTAINER FLUID -->
<!--         </div> -->
        <!-- END PAGE CONTENT -->



        <!-- START FOOTER -->
  <%= render "layouts/footer" %>
        <!-- END FOOTER -->
      </div>
      <!-- END PAGE CONTENT WRAPPER -->
    </div>
    <!-- END PAGE CONTAINER -->

app/views/kiosks/invited.html.erb
<!-- START PAGE-CONTAINER -->
    <div class="page-container">
      <!-- START PAGE HEADER WRAPPER -->
      <!-- START HEADER -->
      <div class="header ">          
        <div class=" pull-left sm-table">
          <div class="header-inner">
        
                      <div class="brand inline">
              <!--
<img src="assets/img/logo.png" alt="logo" data-src="assets/img/logo.png" data-src-retina="assets/img/logo_2x.png" width="78" height="22">
             
-->
            </div> 
            
          </div>
        </div>
        <div class=" pull-right">
          <!-- START User Info-->
          <div class="visible-lg visible-md m-t-10">
            <div class="pull-left p-r-10 p-t-10 fs-16 font-heading">
              <span class="semi-bold">Secure</span> <span class="text-master">Form</span>
            </div>
            <div class="dropdown pull-right">
              <button class="profile-dropdown-toggle" type="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                <span class="thumbnail-wrapper d32 circular inline m-t-5">
                <%= image_tag("avatar.jpg", :alt => "", :size => "32x32",  data: { src: "avatar.jpg", src_retina: "avatar.jpg" }) %>
            </span>
              </button>
            </div>
          </div>  
          <!-- END User Info-->
        </div>
      <!-- END HEADER -->
    </div>    


    <!-- START PAGE-CONTAINER -->
    <div class="page-container pull-left">

      
      
      


           <!-- START PAGE CONTENT WRAPPER -->
<!--       <div class="page-content-wrapper"> -->
        <!-- START PAGE CONTENT -->
        <div class="content">
          <!-- START CONTAINER FLUID -->
          <div class="container-fluid container-fixed-lg">
            <div id="rootwizard">
              <!-- Nav tabs -->
              <ul class="nav nav-tabs nav-tabs-linetriangle nav-tabs-separator ">
        
                <li class="">
                  <a data-toggle="tab" href="#tab3"><i class="fa fa-check tab-icon"></i> <span>Done</span></a>
                </li>
              </ul>
              <!-- Tab panes -->
              <div class="tab-content">
                
                
                
                
     
                <div class="tab-pane slide-left padding-20" id="tab3">
						<h2>Mails have been sent out!</h2>
                    <br />
                        <%=link_to "All Done! Start Over", invite_churches_path(@church), :class => "btn btn-primary btn-cons pull-left", :role => "button"%>
<br />
				</div>
                </div>
                
                
                
                
                



                      
                </div>
                
                
                
                
                             
          
          
          
          
          
          
          
                
                
              </div>
              
            </div>
                               
          </div>   

          <!-- END CONTAINER FLUID -->
<!--         </div> -->
        <!-- END PAGE CONTENT -->
      
      
  <%= render "layouts/footer" %>

      </div>
      <!-- END PAGE CONTENT WRAPPER -->
    </div>
    <!-- END PAGE CONTAINER -->

app/views/kiosks/success.html.erb
<!-- START PAGE-CONTAINER -->
    <div class="page-container">
      <!-- START PAGE HEADER WRAPPER -->
      <!-- START HEADER -->
      <div class="header ">
        <div class=" pull-left sm-table">
          <div class="header-inner">

          <h3 class="pull-left p-l-30"><strong><%= @kiosk.title %></strong></h3>

            <div class="brand inline">
              <!--
<img src="assets/img/logo.png" alt="logo" data-src="assets/img/logo.png" data-src-retina="assets/img/logo_2x.png" width="78" height="22">

-->
            </div>

          </div>
        </div>
        <div class=" pull-right">
          <!-- START User Info-->
          <div class="visible-lg visible-md m-t-10">
            <div class="pull-left p-r-10 p-t-10 fs-16 font-heading">
              <span class="semi-bold">Secure</span> <span class="text-master">Form</span>
            </div>
            <div class="dropdown pull-right">
              <button class="profile-dropdown-toggle" type="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                <span class="thumbnail-wrapper d32 circular inline m-t-5">
                <%= image_tag("avatar.jpg", :alt => "", :size => "32x32",  data: { src: "avatar.jpg", src_retina: "avatar.jpg" }) %>
            </span>
              </button>
            </div>
          </div>
          <!-- END User Info-->
        </div>
      <!-- END HEADER -->
    </div>


    <!-- START PAGE-CONTAINER -->
    <div class="page-container pull-left">






           <!-- START PAGE CONTENT WRAPPER -->
<!--       <div class="page-content-wrapper"> -->
        <!-- START PAGE CONTENT -->
        <div class="content">
          <!-- START CONTAINER FLUID -->
          <div class="container-fluid container-fixed-lg">
            <div id="rootwizard">
              <!-- Nav tabs -->
              <ul class="nav nav-tabs nav-tabs-linetriangle nav-tabs-separator ">

                <li class="">
                  <a data-toggle="tab" href="#tab3"><i class="fa fa-check tab-icon"></i> <span>Done</span></a>
                </li>
              </ul>
              <!-- Tab panes -->
              <div class="tab-content">





                <div class="tab-pane slide-left padding-20" id="tab3">
						<h2>Thank you so much for your payment!</h2>
                    <br />
                        <%=link_to "All Done! Start Over", kiosk_path(@kiosk), :class => "btn btn-primary btn-cons pull-left", :role => "button"%>
<br />
				</div>
                </div>









                </div>














              </div>

            </div>

          </div>

          <!-- END CONTAINER FLUID -->
<!--         </div> -->
        <!-- END PAGE CONTENT -->



        <!-- START FOOTER -->
    <%= render "layouts/footer" %>
        <!-- END FOOTER -->
      </div>
      <!-- END PAGE CONTENT WRAPPER -->
    </div>
    <!-- END PAGE CONTAINER -->

app/views/kiosks/update.js-del.erb
$("#ajx-loader").addClass("hide")
<% if @response['errors'] != nil %>
  $(".payment-errors").html("<%=@response['errors'] %>").removeClass("hide")
  $('#rootwizard').find('.pager .previous').show();
<% elsif @response['status'] != nil %>
  $("#tab3").html('Thank you. Payment has been successfully made for the amount of USD <%= number_to_currency(@response['amount'])%> to <%= @response['title']%>. <br /> Your receipt has been sent. This page will automatically reset in 10 seconds for your security.');
  $("#pager-cont").hide()
  $(".payment-info").html("Your payment reference id is : <%= @response['retref']%>").removeClass("hide")
  setTimeout(function(){  location.reload(); },10000);

<% end%>

app/views/kiosks/update.js.erb
$("#ajx-loader").addClass("hide")
<% if @response['errors'] != nil %>
  $(".payment-errors").html("<%=@response['errors'] %>").removeClass("hide")
  $('#rootwizard').find('.pager .previous').show();
<% elsif @response['status'] != nil %>
  $("#tab3").html('Thank you. Payment has been successfully made for the amount of USD <%= number_to_currency(@response['amount'])%> to <%= @response['title']%>. <br /> Your receipt has been sent. This page will automatically reset in 10 seconds for your security.');
  $("#pager-cont").hide()
  $(".payment-info").html("Your payment reference id is : <%= @response['retref']%>").removeClass("hide")
  setTimeout(function(){  location.reload(); },10000);

<% end%>